services:
  - type: worker
    name: veltrix-downloader
    runtime: docker
    plan: starter
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
