services:
  - type: web
    name: veltrix-downloader
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python render_free.py
    envVars:
      - key: BOT_TOKEN
        sync: false
